### ISSUE TITLE
mfbase init error while having minimal_level=DEBUG

### ISSUE THREAD

**Issue by matthieumarrast** [metwork-framework/mfbase#206]
if the mfbase setting `minimal_level` is set to DEBUG, mfbase refuse to start services:

```
[mfbase:~]↥ $ mfbase.init
*****************************************
*****     MFBASE INITIALIZATION     *****
*****************************************
  
- Stopping (if running) mfbase module...                   [ OK ]     
- Cleaning /home/mfbase/tmp...                             [ OK ]     
- Cleaning /home/mfbase/var...                             [ OK ]     
- Cleaning /home/mfbase/log...                             [ OK ]     
- Checking postgresql data dir...                          [ OK ]     
- Preparing postgresql data dir...                         [ OK ]     
- Starting postgresql initdb...                            [ OK ]     
- (pre)Starting mfbase services...                         [ ERROR ]  
=> EXITING
```

`circus.log`
```
*****************************************************************************   
 2 mar. sept. 20 15:54:59 CEST 2022 : STARTING circus                              
 3 *****************************************************************************   
 4 Traceback (most recent call last):                                              
 5   File "/opt/metwork-mfext-2.0/opt/python3_circus/bin/circusd", line 8, in <module>
 6     sys.exit(main())                                                            
 7   File "/opt/metwork-mfext-2.0/opt/python3_circus/lib/python3.9/site-packages/circus/circusd.py", line 126, in main
 8     arbiter = Arbiter.load_from_config(args.config)                             
 9   File "/opt/metwork-mfext-2.0/opt/python3_circus/lib/python3.9/site-packages/circus/arbiter.py", line 425, in load_from_config
10     cfg = get_config(config_file)                                               
11   File "/opt/metwork-mfext-2.0/opt/python3_circus/lib/python3.9/site-packages/circus/config.py", line 136, in get_config
12     cfg, cfg_files_read = read_config(config_file)                              
13   File "/opt/metwork-mfext-2.0/opt/python3_circus/lib/python3.9/site-packages/circus/config.py", line 101, in read_config
14     cfg.read_file(f)                                                            
15   File "/opt/metwork-mfext-2.0/opt/python3_core/lib/python3.9/configparser.py", line 718, in read_file
16     self._read(f, source)                                                       
17   File "/opt/metwork-mfext-2.0/opt/python3_circus/lib/python3.9/site-packages/circus/util.py", line 803, in _read
18     raise MissingSectionHeaderError(fpname, lineno, line)                       
19 configparser.MissingSectionHeaderError: File contains no section headers.       
20 file: '/home/mfbase/tmp/config_auto/circus.ini', line: 1                        
21 '2022-09-20T13:54:59.583383Z    [DEBUG] (mfutil#140824) /home/mfbase/var/plugins directory created\n'
```

**Comment by matthieumarrast** [comment]
Workaround:

in file `/opt/metwork-mfext-2.0/opt/python3/lib/python3.9/site-packages/mfutil/misc.py`

comment below lines on line 108/109:
```
#if not nodebug:
    #    __get_logger().debug("%s directory created", path)
```
